### ISSUE TITLE
practica de operaciones  basica s

### ISSUE THREAD

**Issue by 71santiago7** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-71santiago7#1]
[Uploading practica de opereciones basicas Rene santiago.pdf…]()

**Comment by josealfredo79** [comment]
Falta la calificación de acuerdo a rúbrica

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by ErickRamos99** [comment]
20%/20%

Excelente trabajo todo esta bien.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
